### ISSUE TITLE
Custom crack size for phase field model

### ISSUE THREAD

**Issue by rperera12** [ISM-Weimar/DeepEnergyMethods#2]
Hi, 
For the phase field model, if we'd like to change the crack size to let's say 0.25 instead 0.5 where can we make this modification in the code

**Comment by somdattagoswami** [comment]
In the class "CalculateUPhi", you need to change self.crackTip = 0.25.

**Comment by rperera12** [comment]
Got it, thanks a lot! Very nice and straight forward implementation. 
An additional question, I tried changing self.crackTip to 0.25 after training the custom code using self.crackTip=0.5, but the prediction is still showing as if the crack size is 0.5. Is the code required to be re-trained for each time we change the crack size to a different value? If so, should I look at one of your most recent works to address this? 
Also, I have changed the material properties around a few times and the predictions are still very accurate which is impressive, that is why I am hoping the crack size is also modifiable after training using self.crackTip=0.5

**Comment by somdattagoswami** [comment]
The network is trained for a specific crack size. To obtain results for different crack lengths, by training a single network, you may want to have a look at our other work on physics-informed DeepONet (https://arxiv.org/abs/2108.06905).
